### ISSUE TITLE
Set Time

### ISSUE THREAD

**Issue by Pukkahq** [dchesterton/texecom2mqtt-hassio#114]
I see its possible to set the time on the alarm panel. texecom2mqtt/datetime

Anyone have an example on how to make it work?

**Comment by Pukkahq** [comment]
To answer my own question, create a script and then create an automation to run it daily.

sequence:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      topic: texecom2mqtt/datetime
      payload: "{{ now().isoformat() }}"
alias: Alarm Time MQTT
description: "Publishes current datetime to texecom2mqtt/datetime"

**Comment by yaminahacs** [comment]
You may use wintex to sync time

**Comment by Pukkahq** [comment]
The script that I posted has been working great.

**Comment by soosp** [comment]
> The script that I posted has been working great.

Thank you to figure ot this.

If you want a time sync button for your alarm panel, you may add a similar entry  to the `configuration.yaml`

```
mqtt:
  - button:
      unique_id: input_button.texecom2mqtt_time_sync
      name: "Time sync"
      command_topic: "texecom2mqtt/datetime"
      command_template: >
        {{ now().isoformat() }}
      availability:
        - topic: "texecom2mqtt/status"
      qos: 0
      retain: false
      entity_category: "config"
      device:
        identifiers: "1234567"
```

The necessary identifier can be found in topic: `homeassistant/alarm_control_panel/texecom2mqtt/your_area_name/config`
