### ISSUE TITLE
Area mapping not working

### ISSUE THREAD

**Issue by madmic1314** [dchesterton/texecom2mqtt-hassio#2]
Hi - for the life of me I can't make the area mapping work:
[texe_error.txt](https://github.com/dchesterton/texecom2mqtt-hassio/files/5314019/texe_error.txt)
homeassistant:
  discovery: true
  prefix: homealarm
  areas:
    area_a:
      mapping:
        full_arm: armed_away

no matter what I put in the area_a mapping it always sends "ARM_AWAY" to texecom2mqtt/1234567/area/area_a/command topic.

The logs show:
WARNING: Unknown command ARM_AWAY for area Area A

Any idea what I'm doing wrong?

**Comment by perimore** [comment]
Here's an example of below. I found that on the panel I had to give the area, "A" a name.  I also think you could replace "area_a" with "A".

```homeassistant:
  discovery: true
  areas:
    house:
      mapping:
        full_arm: armed_away
        part_arm_1: armed_night
        part_arm_2: armed_home
        disarm: disarmed
      options:
        code_arm_required: false```

**Comment by dchesterton** [comment]
@madmic1314 sorry for the delay replying, did you get this working ok in the end?

**Comment by madmic1314** [comment]
Hi, afraid not - tried changing the area name on the HA config to "house". Do I need to change this name on the texecom? It's set as A at the moment. Easy to change.

**Comment by dchesterton** [comment]
The name in the config needs to match the name in Texecom so if you've called it house in the config then you'll need to rename it to the same on the panel.

Alternatively, you can use the area number instead which will work even if you rename the area, e.g.

```
homeassistant:
  discovery: true
  prefix: homealarm
  areas:
    1:
      mapping:
        full_arm: armed_away
```

**Comment by madmic1314** [comment]
Hi @dchesterton yep that fixed it :) No idea why it didn't like the area name. Saved me from going in and changing it. Thanks for the help.

**Comment by silfax** [comment]
ok, i may be an idiot, but i did everything of the above without any result. i keep receiving the same warning:

**WARNING: Unknown command ARM_AWAY for area XXXXX 44**

i've tried replacing the area name with A and 1, tried with and without code, but nothing works.

the system is Elite 88, the addon can read the config:

**2022-12-26 19:47:19 - INFO: Fetched Area A: XXXXX 44**

my yaml below:

```
homeassistant:
  discovery: true
  areas:
    XXXXX 44:
      mapping:
        full_arm: armed_away
      options:
        code: 1234
        code_arm_required: true
        code_disarm_required: true
```
thanks in advance!
