### ISSUE TITLE
ECONNREFUSED - Cannot Connect

### ISSUE THREAD

**Issue by meatalhead** [dchesterton/texecom2mqtt-hassio#28]
**Describe the bug**
After recovering from a corrupt SD card I'm unable to connect to my SmartCom

**Application version**
v.1.1.5

**Texecom alarm type**
Premier Elite 48

**Home Assistant version**
Home Assistant 2021.9.7 - Running in Docker

**Debug log**

> 2021-09-22 14:07:28 - INFO: Starting texecom2mqtt v1.1.5...
> 2021-09-22 14:07:28 - ERROR: connect ECONNREFUSED 192.168.1.180:10001
> 2021-09-22 14:07:28 - DEBUG: Panel socket closed
> 2021-09-22 14:07:28 - INFO: Panel disconnected, exiting now
> 

**Config**
```
`texecom:
    host: 192.168.1.180 # Required: Texecom panel IP address
    udl_password: !secrets udl_password # Optional: UDL password programmed in the panel. Note: this is NOT the code used to arm/disarm the panel (default: 1234)
    port: 10001 # Optional: port used to connect to the panel (default: 10001)

mqtt:
    host: !secrets host_IP # Optional: broker URL or IP address (default: localhost)
    port: 1883 # Optional: broker port (default: 1883 or 8883 for TLS connections)
   # prefix: texecom2mqtt # Optional: topic prefix to use (default: texecom2mqtt)
    username: !secrets username # Optional: broker user (default: none)
    password: !secrets password # Optional: broker password (default: none)
   # client_id: texecom2mqtt # Optional: client ID (default: random)
    keepalive: 30 # Optional: keepalive in seconds (default: 10)
    retain: true # Optional: retain (default: true)
   # retain_log: false # Optional: retain on log messages (default: false)
   # qos: 2 # Optional: QoS (default: 0)
   # ca: /cert/ca.pem # Optional: CA for TLS connection (default: none)
   # cert: /cert/cert.pem # Optional: certificate for TLS connection (default: none)
   # key: /cert/key.pem # Optional: private key for TLS connection (default: none)

homeassistant:
    discovery: true # Optional: enable Home Assistant discovery (default: false)
    prefix: home-assistant # Optional: Home Assistant MQTT topic prefix (default: homeassistant)

# Optional: required only if you want to override a zone name or device class
#zones:
#    - id: front_door # Required: zone number or ID (e.g. 'front_door' or '4')
#      name: Front Door Sensor # Optional: override the zone name (default: zone name in panel)
#      device_class: motion # Optional: set the Home Assistant device class for a zone (default: the app will guess based on zone name and type). See https://www.home-assistant.io/integrations/binary_sensor/#device-class for available d$
#
#    - id: ...
#      name: ...

# Optional: required only for Home Assistant mapping
#areas:
#    - id: house # Required: area number or ID (e.g. 'detached_garage', '4A' or '2')
#      name: House Alarm # Optional: override the area name (default: area name in panel)
#      full_arm: armed_away # Optional: mappings of Texecom arm types to Home Assistant arm types (armed_away, armed_home, armed_night, armed_custom_bypass), omit any which are not relevant
#      part_arm_1: armed_night
#      part_arm_2: armed_home
#      part_arm_3: armed_custom_bypass
#      code_arm_required: false # Optional: see https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/#code_arm_required
#      code_disarm_required: false # Optional: see https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/#code_disarm_required
#      code: "123456" # Optional: see https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/#code
#    - id: ...
#      name: ...

log: debug # Optional: trace, debug, panel, info, warning or error (default: info)
`

```
