### ISSUE TITLE
Trigger action

### ISSUE THREAD

**Issue by perimore** [dchesterton/texecom2mqtt-hassio#6]
Does the Texecom API support a trigger action? The alarm_control_panel code has support for the front end but mapping "trigger" doesn't work.

https://github.com/home-assistant/core/tree/master/homeassistant/components/alarm_control_panel

**Comment by dchesterton** [comment]
I'm not sure what you're asking, sorry, can you explain? The entity state will change to `triggered` if the alarm is triggered.

You can do something like this in your Home Assistant automations to perform an action if the alarm is triggered:

```
alias: "Alarm: triggered"
trigger:
  platform: state
  entity_id: alarm_control_panel.alarm
  to: triggered
action:
...
```
```
