### ISSUE TITLE
AddOn crashes regularly 

### ISSUE THREAD

**Issue by Infeconex** [dchesterton/texecom2mqtt-hassio#79]
**Describe the bug**
I have this installed in the field and am finding that the addon starts without any problems, but within a 24 hour period will stop. I can restart the addon and everything comes back to life, but it will just stop again within another 24 hours.

**Application version**
texecom2mqtt v1.2.3 (Node v16.13.0)

**Texecom alarm type**
I believe it is a Premier Elite 48, with ComIP ... I'm just confirming.

**Home Assistant version**
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Debug log**
The issue I have is that when the addon is stopped - the log is gone from the UI. Starting the log, presents the log from the point the addon starts. Is there a way to pull the historical logs? I want to understand the trigger causing the addon to stop. The 'watchdog' function is not picking up that the addon has stopped, so I am calling the start addon service every 30mins as a workaround for the moment.

**Comment by garethp85** [comment]
I am facing a similar issue.

**Comment by TonyJr1** [comment]
I have the same setup and panel model, experiencing the same issue. Isn’t Watchdog supposed to re-start it again? I have that enabled and it does not restart.

**Comment by Infeconex** [comment]
I'm getting the same, and with no support from the original dev for this integration. I'm left scratching my head about what to do. My only viable option looks to be ripping out the alarm panel and replacing it. I would much rather keep the investment. But with the AddOn crashing, all my motion based automations are failing.

**Comment by metaljay** [comment]
> After updating to the newest alarm and smartcom firmware and utilizing a separate comwifi for HA and smartcom for the texecom app, the issue has improved. However, the texecom smartcom does not work well while linked to both the app and the HA. many disconnections. I put an automation in to start the texecom2mqtt after 15 mins if it's disconnected too


sorry to bump this, but can you add any more detail on your automation to restart texecom2mqtt if it disconnects? is this from home assistant? I running all my stuff via docker

**Comment by shababyousaf** [comment]
yes that's correct the automation is from home assistant

**Comment by cjoha** [comment]
This is the automation I have in HA. TBH, it still doesn't detect the failure reliably. Without @dchesterton being around to help, I think this integration is going to continue to be a challenge to work reliably. I'm thinking that Konnected is the next best step for me.

```
alias: Texecom - Auto reRestart
description: Restarts the texecom addon when it's been down more than 5 mins
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.area_a
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
condition: []
action:
  - data:
      addon: c15a2434_texecom2mqtt
    action: hassio.addon_start
mode: single
```

Note, you'll need to adjust the `entity_id` and `addon` entries to suit your system setup.
