### ISSUE TITLE
Trying to add the area configuration

### ISSUE THREAD

**Issue by brijvs** [dchesterton/texecom2mqtt-hassio#83]
I'm trying to add the area configuration. However it returns an error saying the configuration is invalid. 

My config is as follows

```
texecom:
  host: 192.xxx.xxx.xxx
  udl_password: "xxxx"
  port: 10001
mqtt:
  host: core-mosquitto
  username: homeassistant
  password: xxxxxx
homeassistant:
  discovery: true
areas:
  id: house
  name: House Alarm
  full_arm: armed_away
  part_arm_1: armed_night
  part_arm_2: armed_home
  part_arm_3: armed_custom_bypass

```
**Application version**
Current version: 1.2.3

**Texecom alarm type**
Premier Elite 48

**Home Assistant version**
2023.3.4

**Debug log**

```Failed to save add-on configuration, Invalid list for option 'areas' in texecom2mqtt (c15a2434_texecom2mqtt). Got {'texecom': {'host': '192.xxx.xxx.xxx', 'udl_password': 'xxxx', 'port': 10001}, 'mqtt': {'host': 'core-mosquitto', 'username': 'homeassistant', 'password': 'xxxx'}, 'homeassistant': {'discovery': True}, 'areas': {'id': 'house', 'name': 'House Alarm', 'full_arm': 'armed_away', 'part_arm_1': 'armed_night', 'part_arm_2': 'armed_home', 'part_arm_3': 'armed_custom_bypass'}, 'zones': []}```
